import Foundation

// MARK: - Quest catalog (25 quests)
enum QuestCatalog {
    static let quests: [Quest] = [
        Quest(id: 0,
              title: "The Prior's First Charge",
              brief: "Restore the smallest of the lost pages: any one cross.",
              goalText: "Discover 1 hybrid by performing any cross.",
              requirement: .discoverHybrids(count: 1),
              reward: QuestReward(coins: 30, favor: 2, seeds: [SeedReward(speciesId: 0, quantity: 2)])),
        Quest(id: 1,
              title: "Choir of Mosses",
              brief: "The choir loft must be re-mossed by harvest.",
              goalText: "Discover 4 hybrid entries within the Bryophyta family.",
              requirement: .discoverFamily(.bryophyta, count: 4),
              reward: QuestReward(coins: 60, favor: 4, seeds: [SeedReward(speciesId: 8, quantity: 2)])),
        Quest(id: 2,
              title: "Frond of Pages",
              brief: "The scriptorium asks for new fern-page stencils.",
              goalText: "Discover 4 hybrid entries within the Pteridophyta family.",
              requirement: .discoverFamily(.pteridophyta, count: 4),
              reward: QuestReward(coins: 70, favor: 4, seeds: nil)),
        Quest(id: 3,
              title: "Grove for the Bell",
              brief: "Encircle the new bell with conifers.",
              goalText: "Discover 4 hybrid entries within the Coniferae family.",
              requirement: .discoverFamily(.coniferae, count: 4),
              reward: QuestReward(coins: 80, favor: 4, seeds: nil)),
        Quest(id: 4,
              title: "Reliquary Beds",
              brief: "Restore the high garden's flowering beds.",
              goalText: "Discover 4 hybrid entries within the Angiosperma family.",
              requirement: .discoverFamily(.angiosperma, count: 4),
              reward: QuestReward(coins: 90, favor: 5, seeds: nil)),
        Quest(id: 5,
              title: "Devouring Saints",
              brief: "Curate the strange wing of the herbarium.",
              goalText: "Discover 4 hybrid entries within the Carnivora family.",
              requirement: .discoverFamily(.carnivora, count: 4),
              reward: QuestReward(coins: 110, favor: 6, seeds: nil)),
        Quest(id: 6,
              title: "First Visitors",
              brief: "Welcome the first pilgrims of spring.",
              goalText: "Satisfy 3 visitors.",
              requirement: .satisfyVisitors(count: 3),
              reward: QuestReward(coins: 30, favor: 2, seeds: nil)),
        Quest(id: 7,
              title: "Faithful Visitors",
              brief: "Build the cloister's reputation.",
              goalText: "Satisfy 12 visitors.",
              requirement: .satisfyVisitors(count: 12),
              reward: QuestReward(coins: 90, favor: 5, seeds: nil)),
        Quest(id: 8,
              title: "Patron's Pleasure",
              brief: "Lady Marisette will fund a new wing.",
              goalText: "Satisfy 30 visitors.",
              requirement: .satisfyVisitors(count: 30),
              reward: QuestReward(coins: 240, favor: 14, seeds: nil)),
        Quest(id: 9,
              title: "Silver for the Roof",
              brief: "The cloister roof needs slate.",
              goalText: "Accumulate 200 silver.",
              requirement: .accumulateCoins(200),
              reward: QuestReward(coins: 0, favor: 4, seeds: nil)),
        Quest(id: 10,
              title: "Silver for the Belfry",
              brief: "The belfry beams are rotted.",
              goalText: "Accumulate 600 silver.",
              requirement: .accumulateCoins(600),
              reward: QuestReward(coins: 0, favor: 8, seeds: nil)),
        Quest(id: 11,
              title: "Founder's Tithe",
              brief: "An anniversary worth a grand purse.",
              goalText: "Accumulate 1500 silver.",
              requirement: .accumulateCoins(1500),
              reward: QuestReward(coins: 0, favor: 14, seeds: nil)),
        Quest(id: 12,
              title: "A Mature Garden",
              brief: "Raise the cloister's first generation.",
              goalText: "Own 5 plants at mature stage.",
              requirement: .ownPlantsOfStage(.mature, count: 5),
              reward: QuestReward(coins: 50, favor: 3, seeds: nil)),
        Quest(id: 13,
              title: "A Flowering Cloister",
              brief: "The cloister blooms only with care.",
              goalText: "Own 8 plants at flowering stage.",
              requirement: .ownPlantsOfStage(.flowering, count: 8),
              reward: QuestReward(coins: 110, favor: 6, seeds: nil)),
        Quest(id: 14,
              title: "Seedfall",
              brief: "Save the seed of every plant you can.",
              goalText: "Own 6 plants at seeding stage.",
              requirement: .ownPlantsOfStage(.seeding, count: 6),
              reward: QuestReward(coins: 140, favor: 7, seeds: nil)),
        Quest(id: 15,
              title: "Rare to Market",
              brief: "Sell a rare specimen to the market.",
              goalText: "Sell 1 rare specimen.",
              requirement: .sellRarity(.rare, count: 1),
              reward: QuestReward(coins: 50, favor: 4, seeds: nil)),
        Quest(id: 16,
              title: "Reputation in Rare",
              brief: "The cloister's name spreads via rarities.",
              goalText: "Sell 5 rare specimens.",
              requirement: .sellRarity(.rare, count: 5),
              reward: QuestReward(coins: 150, favor: 8, seeds: nil)),
        Quest(id: 17,
              title: "The Mythic Page",
              brief: "Find one mythic plant before winter.",
              goalText: "Sell 1 mythic specimen.",
              requirement: .sellRarity(.mythic, count: 1),
              reward: QuestReward(coins: 250, favor: 14, seeds: nil)),
        Quest(id: 18,
              title: "Pages of the Lost Herbarium",
              brief: "Restore the herbarium's heart.",
              goalText: "Discover 20 hybrids.",
              requirement: .discoverHybrids(count: 20),
              reward: QuestReward(coins: 180, favor: 12, seeds: nil)),
        Quest(id: 19,
              title: "The Long Herbarium",
              brief: "The middle pages.",
              goalText: "Discover 60 hybrids.",
              requirement: .discoverHybrids(count: 60),
              reward: QuestReward(coins: 450, favor: 24, seeds: nil)),
        Quest(id: 20,
              title: "Closing Pages",
              brief: "Toward the final page.",
              goalText: "Discover 120 hybrids.",
              requirement: .discoverHybrids(count: 120),
              reward: QuestReward(coins: 900, favor: 40, seeds: nil)),
        Quest(id: 21,
              title: "The Cathedral Tree",
              brief: "Cultivate the Cathedral Tree Fern.",
              goalText: "Discover species \"Cathedral Tree Fern\".",
              requirement: .discoverSpecies(speciesId: 29),
              reward: QuestReward(coins: 90, favor: 6, seeds: nil)),
        Quest(id: 22,
              title: "The Black Tulip",
              brief: "Witness the Mythic Black Tulip.",
              goalText: "Discover species \"Mythic Black Tulip\".",
              requirement: .discoverSpecies(speciesId: 62),
              reward: QuestReward(coins: 130, favor: 8, seeds: nil)),
        Quest(id: 23,
              title: "Snap-Vine Rumour",
              brief: "Verify the southern rumour.",
              goalText: "Discover species \"Sanctum Snap-Vine\".",
              requirement: .discoverSpecies(speciesId: 79),
              reward: QuestReward(coins: 150, favor: 9, seeds: nil)),
        Quest(id: 24,
              title: "Royal Couriers",
              brief: "Win the king's notice.",
              goalText: "Sell 10 uncommon specimens.",
              requirement: .sellRarity(.uncommon, count: 10),
              reward: QuestReward(coins: 200, favor: 12, seeds: nil))
    ]
}

// MARK: - Achievements (30)
enum AchievementCatalog {
    static let achievements: [Achievement] = [
        Achievement(id: 0, title: "First Cross", brief: "Perform your first cross.", requirement: .discoverHybrids(1)),
        Achievement(id: 1, title: "A Dozen Pages", brief: "Discover 12 hybrid pages.", requirement: .discoverHybrids(12)),
        Achievement(id: 2, title: "Thirty Pages", brief: "Discover 30 hybrid pages.", requirement: .discoverHybrids(30)),
        Achievement(id: 3, title: "Restorer", brief: "Discover 80 hybrid pages.", requirement: .discoverHybrids(80)),
        Achievement(id: 4, title: "Master Curator", brief: "Discover all 160 hybrid pages.", requirement: .discoverHybrids(160)),
        Achievement(id: 5, title: "Moss Cataloguer", brief: "Discover 12 Bryophyta hybrid entries.", requirement: .discoverFamily(.bryophyta, 12)),
        Achievement(id: 6, title: "Fern Cataloguer", brief: "Discover 12 Pteridophyta hybrid entries.", requirement: .discoverFamily(.pteridophyta, 12)),
        Achievement(id: 7, title: "Conifer Cataloguer", brief: "Discover 12 Coniferae hybrid entries.", requirement: .discoverFamily(.coniferae, 12)),
        Achievement(id: 8, title: "Bloom Cataloguer", brief: "Discover 12 Angiosperma hybrid entries.", requirement: .discoverFamily(.angiosperma, 12)),
        Achievement(id: 9, title: "Carnivor Cataloguer", brief: "Discover 12 Carnivora hybrid entries.", requirement: .discoverFamily(.carnivora, 12)),
        Achievement(id: 10, title: "Hospitable", brief: "Satisfy 10 visitors.", requirement: .satisfyVisitors(10)),
        Achievement(id: 11, title: "Famed Hospitality", brief: "Satisfy 50 visitors.", requirement: .satisfyVisitors(50)),
        Achievement(id: 12, title: "Royal Reception", brief: "Satisfy 150 visitors.", requirement: .satisfyVisitors(150)),
        Achievement(id: 13, title: "Patron Saint", brief: "Satisfy Lady Marisette.", requirement: .satisfyArchetype(3)),
        Achievement(id: 14, title: "Mystic's Favor", brief: "Satisfy Heralda the Mystic.", requirement: .satisfyArchetype(18)),
        Achievement(id: 15, title: "King's Notice", brief: "Satisfy the Royal Courier.", requirement: .satisfyArchetype(5)),
        Achievement(id: 16, title: "Lord's Acceptance", brief: "Satisfy Lord Casimir.", requirement: .satisfyArchetype(36)),
        Achievement(id: 17, title: "Frugal Frugal", brief: "Satisfy Foreman Bartol.", requirement: .satisfyArchetype(19)),
        Achievement(id: 18, title: "Healer's Friend", brief: "Satisfy Healer Brigit.", requirement: .satisfyArchetype(38)),
        Achievement(id: 19, title: "Hundred Silver", brief: "Accumulate 100 silver.", requirement: .accumulateCoins(100)),
        Achievement(id: 20, title: "Five Hundred Silver", brief: "Accumulate 500 silver.", requirement: .accumulateCoins(500)),
        Achievement(id: 21, title: "Two Thousand Silver", brief: "Accumulate 2000 silver.", requirement: .accumulateCoins(2000)),
        Achievement(id: 22, title: "A Garden Mature", brief: "Own 10 mature plants.", requirement: .ownPlantsOfStage(.mature, 10)),
        Achievement(id: 23, title: "A Garden in Bloom", brief: "Own 10 flowering plants.", requirement: .ownPlantsOfStage(.flowering, 10)),
        Achievement(id: 24, title: "A Seed Bank", brief: "Own 10 seeding plants.", requirement: .ownPlantsOfStage(.seeding, 10)),
        Achievement(id: 25, title: "First Reward", brief: "Complete your first quest.", requirement: .completeQuest(1)),
        Achievement(id: 26, title: "Quest Master", brief: "Complete 10 quests.", requirement: .completeQuest(10)),
        Achievement(id: 27, title: "Patron of the Cloister", brief: "Own 5 monastery upgrades.", requirement: .ownUpgrade(5)),
        Achievement(id: 28, title: "Architect", brief: "Own 12 monastery upgrades.", requirement: .ownUpgrade(12)),
        Achievement(id: 29, title: "Lord Curator", brief: "Own all 20 monastery upgrades.", requirement: .ownUpgrade(20))
    ]
}

// MARK: - Monastery upgrades (20)
enum UpgradeCatalog {
    static let upgrades: [MonasteryUpgrade] = [
        MonasteryUpgrade(id: 0, name: "Second Pot",
                         description: "Add one additional pot to the cloister yard.",
                         costCoins: 40, costFavor: 0,
                         effect: .addSlots(surface: .pot, slots: 1)),
        MonasteryUpgrade(id: 1, name: "Third Pot",
                         description: "Add one additional pot to the cloister yard.",
                         costCoins: 80, costFavor: 0,
                         effect: .addSlots(surface: .pot, slots: 1)),
        MonasteryUpgrade(id: 2, name: "Fourth Pot",
                         description: "Add one additional pot to the cloister yard.",
                         costCoins: 140, costFavor: 0,
                         effect: .addSlots(surface: .pot, slots: 1)),
        MonasteryUpgrade(id: 3, name: "Raised Bed",
                         description: "Adds a 3-slot bed; slightly faster growth.",
                         costCoins: 120, costFavor: 2,
                         effect: .addSlots(surface: .bed, slots: 3)),
        MonasteryUpgrade(id: 4, name: "Second Raised Bed",
                         description: "Adds another 3-slot bed.",
                         costCoins: 220, costFavor: 4,
                         effect: .addSlots(surface: .bed, slots: 3)),
        MonasteryUpgrade(id: 5, name: "Glass Terrarium",
                         description: "Adds a single-slot terrarium; fastest growth.",
                         costCoins: 200, costFavor: 6,
                         effect: .addSlots(surface: .terrarium, slots: 1)),
        MonasteryUpgrade(id: 6, name: "Second Terrarium",
                         description: "Adds another single-slot terrarium.",
                         costCoins: 360, costFavor: 10,
                         effect: .addSlots(surface: .terrarium, slots: 1)),
        MonasteryUpgrade(id: 7, name: "Almoner's Hours",
                         description: "Permanent +1 daily action.",
                         costCoins: 320, costFavor: 6,
                         effect: .extraDailyAction),
        MonasteryUpgrade(id: 8, name: "Late Vespers Hours",
                         description: "Permanent +1 daily action.",
                         costCoins: 540, costFavor: 12,
                         effect: .extraDailyAction),
        MonasteryUpgrade(id: 9, name: "Charcoal Trade",
                         description: "Unlock charcoal substrate.",
                         costCoins: 80, costFavor: 1,
                         effect: .unlockSubstrate(.charcoal)),
        MonasteryUpgrade(id: 10, name: "Sphagnum Trade",
                         description: "Unlock sphagnum substrate.",
                         costCoins: 60, costFavor: 1,
                         effect: .unlockSubstrate(.sphagnum)),
        MonasteryUpgrade(id: 11, name: "Leaf-Mold Compost",
                         description: "Unlock leaf-mold substrate.",
                         costCoins: 50, costFavor: 0,
                         effect: .unlockSubstrate(.leafMold)),
        MonasteryUpgrade(id: 12, name: "Drying Rack",
                         description: "Quicker recovery of mature plants. +10% growth.",
                         costCoins: 180, costFavor: 4,
                         effect: .fasterGrowth(percent: 10)),
        MonasteryUpgrade(id: 13, name: "Glasshouse",
                         description: "Climate-controlled. +15% growth.",
                         costCoins: 480, costFavor: 12,
                         effect: .fasterGrowth(percent: 15)),
        MonasteryUpgrade(id: 14, name: "Microscope",
                         description: "Scribes see clearly. +10% visitor payment.",
                         costCoins: 260, costFavor: 8,
                         effect: .visitorBonus(percent: 10)),
        MonasteryUpgrade(id: 15, name: "Scribe's Desk",
                         description: "Better record-keeping. +15% visitor payment.",
                         costCoins: 460, costFavor: 14,
                         effect: .visitorBonus(percent: 15)),
        MonasteryUpgrade(id: 16, name: "Well",
                         description: "Wider seed market grants +200 silver.",
                         costCoins: 100, costFavor: 0,
                         effect: .grantCoins(200)),
        MonasteryUpgrade(id: 17, name: "Cloister Bell",
                         description: "Pilgrims double. Permanent +2 favor each day.",
                         costCoins: 400, costFavor: 10,
                         effect: .favorGain(2)),
        MonasteryUpgrade(id: 18, name: "Founder's Chapel",
                         description: "Honors the founder. +10% visitor payment.",
                         costCoins: 700, costFavor: 18,
                         effect: .visitorBonus(percent: 10)),
        MonasteryUpgrade(id: 19, name: "Reliquary Vault",
                         description: "Stores mythic specimens with honor. +1 daily action.",
                         costCoins: 900, costFavor: 24,
                         effect: .extraDailyAction)
    ]
}

// MARK: - Hint pages (Lost Herbarium riddles)
struct HintPage: Identifiable, Hashable {
    let id: Int
    let pageNumber: Int
    let text: String
    let referencedHybridId: Int
}

enum HintCatalog {
    static let pages: [HintPage] = {
        var result: [HintPage] = []
        for (idx, hybridId) in (80..<240).enumerated() {
            if let s = HybridCatalog.species(forId: hybridId) {
                result.append(HintPage(
                    id: idx,
                    pageNumber: idx + 1,
                    text: s.hint,
                    referencedHybridId: hybridId
                ))
            }
        }
        return result
    }()
}
