import Foundation

// MARK: - Hard-coded species catalog
// 80 base species (ids 0-79) across 5 families.
// All names, traits and care presets are deterministic.

enum SpeciesCatalog {
    static let baseSpecies: [Species] = {
        var list: [Species] = []

        // ===== Bryophyta (Mosses) — ids 0-15 =====
        let mosses: [(String, TraitBundle, CarePreset, SpecimenRarity, String)] = [
            ("Cloister Velvet Moss",
             TraitBundle(leaf: .ovate, color: .green, scent: .earthy, lifespan: .perennial, frost: .hardy, drought: .thirsty),
             CarePreset(substrate: .sphagnum, light: .deepShade, humidity: .saturated), .common,
             "A carpet of forest-green that softens any north-facing stone."),
            ("Reliquary Cushion Moss",
             TraitBundle(leaf: .cordate, color: .green, scent: .balsam, lifespan: .perennial, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .sphagnum, light: .dappled, humidity: .damp), .common,
             "Pillow-soft cushions said to insulate saints' bones."),
            ("Lantern Spike Moss",
             TraitBundle(leaf: .needle, color: .green, scent: .earthy, lifespan: .biennial, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .peat, light: .dappled, humidity: .damp), .uncommon,
             "Tiny stalks bear capsule-lanterns at dawn."),
            ("Vesper White Moss",
             TraitBundle(leaf: .ribbon, color: .white, scent: .none, lifespan: .seasonal, frost: .hardy, drought: .thirsty),
             CarePreset(substrate: .sphagnum, light: .deepShade, humidity: .saturated), .uncommon,
             "A pale carpet glimpsed only after evening bell."),
            ("Vermilion Carpet Moss",
             TraitBundle(leaf: .ovate, color: .red, scent: .none, lifespan: .perennial, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .sphagnum, light: .dappled, humidity: .damp), .uncommon,
             "Reddens dramatically in winter frost."),
            ("Sun-Touched Moss",
             TraitBundle(leaf: .ovate, color: .yellow, scent: .none, lifespan: .seasonal, frost: .tender, drought: .balanced),
             CarePreset(substrate: .leafMold, light: .bright, humidity: .mild), .common,
             "Glows gold in late afternoon light."),
            ("Iron Wall Moss",
             TraitBundle(leaf: .lance, color: .green, scent: .earthy, lifespan: .ancient, frost: .glacial, drought: .arid),
             CarePreset(substrate: .gravel, light: .bright, humidity: .dry), .rare,
             "Found on the oldest walls; impossibly hardy."),
            ("Halo Star Moss",
             TraitBundle(leaf: .palmate, color: .white, scent: .honey, lifespan: .biennial, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .sphagnum, light: .dappled, humidity: .damp), .uncommon,
             "Star-shaped tufts ringed in faint honey scent."),
            ("Vespertine Azure Moss",
             TraitBundle(leaf: .ovate, color: .azure, scent: .mint, lifespan: .perennial, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .sphagnum, light: .deepShade, humidity: .saturated), .rare,
             "Cobalt-tinted moss with a faint mint note."),
            ("Glacier Felt Moss",
             TraitBundle(leaf: .cordate, color: .white, scent: .none, lifespan: .ancient, frost: .glacial, drought: .arid),
             CarePreset(substrate: .gravel, light: .fullSun, humidity: .dry), .rare,
             "Felted layer survives where snow lingers."),
            ("Saintly Amber Moss",
             TraitBundle(leaf: .ovate, color: .amber, scent: .honey, lifespan: .perennial, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .leafMold, light: .dappled, humidity: .damp), .uncommon,
             "Warm amber glow; preferred by hive-keepers."),
            ("Ink Pool Moss",
             TraitBundle(leaf: .ovate, color: .violet, scent: .smoke, lifespan: .biennial, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .peat, light: .deepShade, humidity: .saturated), .rare,
             "Sopping wet, almost black; faintly smoky."),
            ("Mendicant Green Moss",
             TraitBundle(leaf: .lance, color: .green, scent: .balsam, lifespan: .perennial, frost: .hardy, drought: .thirsty),
             CarePreset(substrate: .sphagnum, light: .deepShade, humidity: .saturated), .common,
             "The plain green of country chapels."),
            ("Rose-Veiled Moss",
             TraitBundle(leaf: .palmate, color: .rose, scent: .honey, lifespan: .seasonal, frost: .tender, drought: .thirsty),
             CarePreset(substrate: .sphagnum, light: .dappled, humidity: .damp), .uncommon,
             "Faint blush across young growth."),
            ("Hermit's Smoke Moss",
             TraitBundle(leaf: .needle, color: .violet, scent: .smoke, lifespan: .ancient, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .charcoal, light: .deepShade, humidity: .damp), .mythic,
             "Said to scent the cell of every hermit who stays long."),
            ("Choir Loft Moss",
             TraitBundle(leaf: .ovate, color: .green, scent: .balsam, lifespan: .ancient, frost: .glacial, drought: .balanced),
             CarePreset(substrate: .sphagnum, light: .deepShade, humidity: .damp), .rare,
             "Sound-dampening growth above the choir.")
        ]

        for (i, e) in mosses.enumerated() {
            list.append(Species(id: i, name: e.0, family: .bryophyta, traits: e.1, care: e.2, rarity: e.3,
                                isBase: true, parentSpeciesIds: nil, hint: e.4))
        }

        // ===== Pteridophyta (Ferns) — ids 16-31 =====
        let ferns: [(String, TraitBundle, CarePreset, SpecimenRarity, String)] = [
            ("Sanctum Lady Fern",
             TraitBundle(leaf: .lance, color: .green, scent: .earthy, lifespan: .perennial, frost: .hardy, drought: .thirsty),
             CarePreset(substrate: .leafMold, light: .dappled, humidity: .damp), .common,
             "Lacy fronds; the cloister's most reliable fern."),
            ("Hart's-Tongue Cloister Fern",
             TraitBundle(leaf: .ribbon, color: .green, scent: .none, lifespan: .perennial, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .leafMold, light: .deepShade, humidity: .damp), .common,
             "Single ribbon-fronds form a wall of pages."),
            ("Citron Frond Fern",
             TraitBundle(leaf: .lance, color: .yellow, scent: .citrus, lifespan: .seasonal, frost: .tender, drought: .thirsty),
             CarePreset(substrate: .peat, light: .dappled, humidity: .damp), .uncommon,
             "Crushed fronds smell of fresh citron."),
            ("Anchorite Maidenhair",
             TraitBundle(leaf: .palmate, color: .green, scent: .none, lifespan: .perennial, frost: .tender, drought: .thirsty),
             CarePreset(substrate: .leafMold, light: .dappled, humidity: .saturated), .uncommon,
             "Black wire stems, fan-shaped pinnules."),
            ("Ironwall Polypody",
             TraitBundle(leaf: .lobed, color: .green, scent: .earthy, lifespan: .perennial, frost: .glacial, drought: .arid),
             CarePreset(substrate: .gravel, light: .bright, humidity: .dry), .uncommon,
             "Lobed fronds clinging to dry stones."),
            ("Vesper Crescent Fern",
             TraitBundle(leaf: .lobed, color: .azure, scent: .balsam, lifespan: .perennial, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .leafMold, light: .dappled, humidity: .damp), .rare,
             "Fronds curl into crescents at dusk."),
            ("Smoke-Veined Bracken",
             TraitBundle(leaf: .palmate, color: .green, scent: .smoke, lifespan: .perennial, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .peat, light: .bright, humidity: .damp), .uncommon,
             "Smoke-grey veins through each pinnule."),
            ("Glassbead Adder's Tongue",
             TraitBundle(leaf: .lance, color: .white, scent: .mint, lifespan: .seasonal, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .sphagnum, light: .deepShade, humidity: .saturated), .rare,
             "Bears small glass-clear spore beads."),
            ("Vermilion Tip Fern",
             TraitBundle(leaf: .lance, color: .red, scent: .none, lifespan: .biennial, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .leafMold, light: .dappled, humidity: .damp), .uncommon,
             "Each tip flares vermilion in summer."),
            ("Royal Page Fern",
             TraitBundle(leaf: .palmate, color: .amber, scent: .honey, lifespan: .perennial, frost: .tender, drought: .thirsty),
             CarePreset(substrate: .peat, light: .bright, humidity: .damp), .rare,
             "Pages of amber pinnules; courier-favored."),
            ("Mendicant Bracken",
             TraitBundle(leaf: .palmate, color: .green, scent: .earthy, lifespan: .seasonal, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .leafMold, light: .bright, humidity: .mild), .common,
             "Tough fronds; survives the road."),
            ("Hermitage Spleenwort",
             TraitBundle(leaf: .needle, color: .green, scent: .balsam, lifespan: .perennial, frost: .glacial, drought: .arid),
             CarePreset(substrate: .gravel, light: .dappled, humidity: .dry), .uncommon,
             "Needle-fine fronds on bare stone."),
            ("Apothecary Tongue Fern",
             TraitBundle(leaf: .ribbon, color: .yellow, scent: .citrus, lifespan: .biennial, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .leafMold, light: .dappled, humidity: .damp), .uncommon,
             "Faintly citric, prized in syrups."),
            ("Cathedral Tree Fern",
             TraitBundle(leaf: .palmate, color: .green, scent: .none, lifespan: .ancient, frost: .tender, drought: .thirsty),
             CarePreset(substrate: .leafMold, light: .dappled, humidity: .saturated), .mythic,
             "Builds a vaulted ceiling of fronds."),
            ("Mauve Heart Fern",
             TraitBundle(leaf: .cordate, color: .violet, scent: .honey, lifespan: .seasonal, frost: .hardy, drought: .thirsty),
             CarePreset(substrate: .leafMold, light: .dappled, humidity: .damp), .rare,
             "Heart-shaped pinnules in mauve flush."),
            ("Pilgrim Bone Fern",
             TraitBundle(leaf: .lance, color: .white, scent: .musk, lifespan: .ancient, frost: .glacial, drought: .balanced),
             CarePreset(substrate: .gravel, light: .deepShade, humidity: .damp), .rare,
             "Pale, bone-coloured fronds; faintly musky.")
        ]
        for (i, e) in ferns.enumerated() {
            list.append(Species(id: 16 + i, name: e.0, family: .pteridophyta, traits: e.1, care: e.2, rarity: e.3,
                                isBase: true, parentSpeciesIds: nil, hint: e.4))
        }

        // ===== Coniferae (Conifers) — ids 32-47 =====
        let conifers: [(String, TraitBundle, CarePreset, SpecimenRarity, String)] = [
            ("Cloister Pine",
             TraitBundle(leaf: .needle, color: .green, scent: .balsam, lifespan: .ancient, frost: .glacial, drought: .balanced),
             CarePreset(substrate: .loam, light: .fullSun, humidity: .mild), .common,
             "Tall, austere, scent of warm resin."),
            ("Prior's Yew",
             TraitBundle(leaf: .needle, color: .green, scent: .none, lifespan: .ancient, frost: .glacial, drought: .balanced),
             CarePreset(substrate: .loam, light: .dappled, humidity: .mild), .uncommon,
             "Sombre yew said to outlast the priors."),
            ("Ember Larch",
             TraitBundle(leaf: .needle, color: .amber, scent: .smoke, lifespan: .perennial, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .loam, light: .fullSun, humidity: .mild), .uncommon,
             "Needles turn ember-gold in autumn."),
            ("Snowdrift Fir",
             TraitBundle(leaf: .needle, color: .white, scent: .balsam, lifespan: .ancient, frost: .glacial, drought: .balanced),
             CarePreset(substrate: .loam, light: .bright, humidity: .mild), .rare,
             "Frosted needles even in summer."),
            ("Choir Cedar",
             TraitBundle(leaf: .needle, color: .green, scent: .balsam, lifespan: .ancient, frost: .hardy, drought: .arid),
             CarePreset(substrate: .loam, light: .fullSun, humidity: .dry), .uncommon,
             "Cedar smoke perfumes the choir loft."),
            ("Vermilion Juniper",
             TraitBundle(leaf: .needle, color: .red, scent: .smoke, lifespan: .biennial, frost: .glacial, drought: .arid),
             CarePreset(substrate: .gravel, light: .fullSun, humidity: .dry), .rare,
             "Berries bright as cinnabar."),
            ("Sky-Touched Cypress",
             TraitBundle(leaf: .needle, color: .azure, scent: .balsam, lifespan: .perennial, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .loam, light: .bright, humidity: .mild), .rare,
             "Tips wear sky-blue waxy bloom."),
            ("Roselit Hemlock",
             TraitBundle(leaf: .needle, color: .rose, scent: .none, lifespan: .perennial, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .loam, light: .dappled, humidity: .mild), .uncommon,
             "New flush is unexpectedly rose."),
            ("Saint's Spruce",
             TraitBundle(leaf: .needle, color: .green, scent: .honey, lifespan: .ancient, frost: .glacial, drought: .balanced),
             CarePreset(substrate: .loam, light: .fullSun, humidity: .mild), .common,
             "Sap honey-sweet; common around shrines."),
            ("Vesper Yew",
             TraitBundle(leaf: .needle, color: .violet, scent: .musk, lifespan: .ancient, frost: .glacial, drought: .balanced),
             CarePreset(substrate: .loam, light: .deepShade, humidity: .damp), .rare,
             "Turns violet-black in dusk light."),
            ("Pilgrim Pine",
             TraitBundle(leaf: .needle, color: .green, scent: .balsam, lifespan: .perennial, frost: .hardy, drought: .arid),
             CarePreset(substrate: .gravel, light: .fullSun, humidity: .dry), .common,
             "Stunted, gnarled, found by the pilgrim road."),
            ("Ashfall Cedar",
             TraitBundle(leaf: .needle, color: .white, scent: .smoke, lifespan: .ancient, frost: .glacial, drought: .arid),
             CarePreset(substrate: .charcoal, light: .fullSun, humidity: .dry), .mythic,
             "Said to thrive after volcanic ash."),
            ("Hermitage Fir",
             TraitBundle(leaf: .needle, color: .green, scent: .smoke, lifespan: .ancient, frost: .glacial, drought: .balanced),
             CarePreset(substrate: .loam, light: .dappled, humidity: .mild), .uncommon,
             "Wood prized for fire-side hermitages."),
            ("Bright-Crown Pine",
             TraitBundle(leaf: .needle, color: .yellow, scent: .citrus, lifespan: .perennial, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .loam, light: .fullSun, humidity: .mild), .uncommon,
             "Crown gilded gold even in winter."),
            ("Glacial Juniper",
             TraitBundle(leaf: .needle, color: .azure, scent: .mint, lifespan: .ancient, frost: .glacial, drought: .arid),
             CarePreset(substrate: .gravel, light: .fullSun, humidity: .dry), .rare,
             "Wind-blasted alpine juniper."),
            ("Veiled Sequoia",
             TraitBundle(leaf: .needle, color: .green, scent: .balsam, lifespan: .ancient, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .loam, light: .fullSun, humidity: .damp), .mythic,
             "Foggy giant from far across the sea.")
        ]
        for (i, e) in conifers.enumerated() {
            list.append(Species(id: 32 + i, name: e.0, family: .coniferae, traits: e.1, care: e.2, rarity: e.3,
                                isBase: true, parentSpeciesIds: nil, hint: e.4))
        }

        // ===== Angiosperma (Flowering) — ids 48-63 =====
        let blooms: [(String, TraitBundle, CarePreset, SpecimenRarity, String)] = [
            ("Reliquary Rose",
             TraitBundle(leaf: .lobed, color: .red, scent: .honey, lifespan: .perennial, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .loam, light: .fullSun, humidity: .mild), .common,
             "The cloister's signature crimson rose."),
            ("Reliquary White Rose",
             TraitBundle(leaf: .lobed, color: .white, scent: .honey, lifespan: .perennial, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .loam, light: .fullSun, humidity: .mild), .common,
             "Pale twin to the crimson rose."),
            ("Saint Helena Lily",
             TraitBundle(leaf: .ribbon, color: .white, scent: .honey, lifespan: .seasonal, frost: .tender, drought: .balanced),
             CarePreset(substrate: .loam, light: .bright, humidity: .mild), .uncommon,
             "Trumpet-white, the day's first scent."),
            ("Choirstall Violet",
             TraitBundle(leaf: .cordate, color: .violet, scent: .honey, lifespan: .seasonal, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .leafMold, light: .dappled, humidity: .damp), .common,
             "Carpets the floor under choirstalls."),
            ("Almoner's Marigold",
             TraitBundle(leaf: .lobed, color: .yellow, scent: .citrus, lifespan: .seasonal, frost: .tender, drought: .balanced),
             CarePreset(substrate: .loam, light: .fullSun, humidity: .mild), .common,
             "Bright marigold, given to the poor."),
            ("Cloister Iris",
             TraitBundle(leaf: .ribbon, color: .azure, scent: .none, lifespan: .perennial, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .loam, light: .fullSun, humidity: .damp), .uncommon,
             "Spear-leaves with deep blue falls."),
            ("Plainsong Poppy",
             TraitBundle(leaf: .lobed, color: .red, scent: .none, lifespan: .ephemeral, frost: .tender, drought: .balanced),
             CarePreset(substrate: .loam, light: .fullSun, humidity: .mild), .common,
             "Brief crimson, sung over by harvesters."),
            ("Vespertine Hyacinth",
             TraitBundle(leaf: .ribbon, color: .violet, scent: .honey, lifespan: .seasonal, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .loam, light: .bright, humidity: .mild), .uncommon,
             "Scents evening prayer."),
            ("Vermilion Camellia",
             TraitBundle(leaf: .ovate, color: .red, scent: .none, lifespan: .perennial, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .leafMold, light: .dappled, humidity: .damp), .uncommon,
             "Dense crimson cup-blooms in winter."),
            ("Gilded Buttercup",
             TraitBundle(leaf: .palmate, color: .yellow, scent: .none, lifespan: .seasonal, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .clay, light: .fullSun, humidity: .damp), .common,
             "Cup catches and reflects sunlight."),
            ("Rose-Tongued Foxglove",
             TraitBundle(leaf: .lance, color: .rose, scent: .honey, lifespan: .biennial, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .leafMold, light: .dappled, humidity: .damp), .uncommon,
             "Tall spires with rose throats."),
            ("Citron Wallflower",
             TraitBundle(leaf: .lance, color: .yellow, scent: .citrus, lifespan: .biennial, frost: .hardy, drought: .arid),
             CarePreset(substrate: .gravel, light: .fullSun, humidity: .dry), .common,
             "Bright lemon-scented walls."),
            ("Apothecary Borage",
             TraitBundle(leaf: .ovate, color: .azure, scent: .mint, lifespan: .seasonal, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .loam, light: .fullSun, humidity: .mild), .uncommon,
             "Star-blue, cucumber-mint scent."),
            ("Amber Calendula",
             TraitBundle(leaf: .lobed, color: .amber, scent: .balsam, lifespan: .seasonal, frost: .tender, drought: .balanced),
             CarePreset(substrate: .loam, light: .fullSun, humidity: .mild), .uncommon,
             "Used in the infirmary's amber salve."),
            ("Mythic Black Tulip",
             TraitBundle(leaf: .ribbon, color: .violet, scent: .musk, lifespan: .seasonal, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .loam, light: .fullSun, humidity: .mild), .mythic,
             "Goblet so dark it eats the morning."),
            ("White Glory Anemone",
             TraitBundle(leaf: .palmate, color: .white, scent: .none, lifespan: .ephemeral, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .leafMold, light: .dappled, humidity: .damp), .uncommon,
             "Brief, snow-white, gone in three days.")
        ]
        for (i, e) in blooms.enumerated() {
            list.append(Species(id: 48 + i, name: e.0, family: .angiosperma, traits: e.1, care: e.2, rarity: e.3,
                                isBase: true, parentSpeciesIds: nil, hint: e.4))
        }

        // ===== Carnivora — ids 64-79 =====
        let carns: [(String, TraitBundle, CarePreset, SpecimenRarity, String)] = [
            ("Pilgrim Pitcher",
             TraitBundle(leaf: .ribbon, color: .red, scent: .musk, lifespan: .perennial, frost: .tender, drought: .thirsty),
             CarePreset(substrate: .peat, light: .bright, humidity: .saturated), .common,
             "Wayfarer's flask brimming with prey."),
            ("Vesper Sundew",
             TraitBundle(leaf: .ribbon, color: .rose, scent: .honey, lifespan: .perennial, frost: .hardy, drought: .thirsty),
             CarePreset(substrate: .peat, light: .bright, humidity: .saturated), .uncommon,
             "Sticky pinpoints glitter at vespers."),
            ("Cloister Venus Trap",
             TraitBundle(leaf: .lobed, color: .green, scent: .smoke, lifespan: .perennial, frost: .tender, drought: .thirsty),
             CarePreset(substrate: .peat, light: .fullSun, humidity: .damp), .uncommon,
             "Snaps shut on whichever insect approaches."),
            ("Reliquary Butterwort",
             TraitBundle(leaf: .ovate, color: .violet, scent: .honey, lifespan: .perennial, frost: .hardy, drought: .balanced),
             CarePreset(substrate: .peat, light: .dappled, humidity: .damp), .uncommon,
             "Buttery leaves trap gnats with kindness."),
            ("Citron Pitcher",
             TraitBundle(leaf: .ribbon, color: .yellow, scent: .citrus, lifespan: .perennial, frost: .tender, drought: .thirsty),
             CarePreset(substrate: .peat, light: .fullSun, humidity: .saturated), .rare,
             "Pitcher rim flushes citron-yellow."),
            ("Smoke-Mawed Sarracenia",
             TraitBundle(leaf: .ribbon, color: .violet, scent: .smoke, lifespan: .perennial, frost: .hardy, drought: .thirsty),
             CarePreset(substrate: .peat, light: .bright, humidity: .saturated), .rare,
             "Inside the maw, smoke gathers visibly."),
            ("Mendicant Sundew",
             TraitBundle(leaf: .lance, color: .green, scent: .none, lifespan: .perennial, frost: .hardy, drought: .thirsty),
             CarePreset(substrate: .sphagnum, light: .bright, humidity: .saturated), .common,
             "Plain sundew, anywhere boggy."),
            ("Vermilion Trap",
             TraitBundle(leaf: .lobed, color: .red, scent: .musk, lifespan: .biennial, frost: .tender, drought: .balanced),
             CarePreset(substrate: .peat, light: .fullSun, humidity: .damp), .uncommon,
             "Trap edges seared vermilion."),
            ("Sky Pitcher",
             TraitBundle(leaf: .ribbon, color: .azure, scent: .mint, lifespan: .perennial, frost: .hardy, drought: .thirsty),
             CarePreset(substrate: .peat, light: .bright, humidity: .saturated), .rare,
             "Pitchers tinted sky-blue."),
            ("Hermit's Bog Star",
             TraitBundle(leaf: .palmate, color: .white, scent: .musk, lifespan: .ancient, frost: .glacial, drought: .thirsty),
             CarePreset(substrate: .sphagnum, light: .bright, humidity: .saturated), .mythic,
             "Star-shaped trap, drifting on dark bog water."),
            ("Saintly Trumpet Pitcher",
             TraitBundle(leaf: .ribbon, color: .amber, scent: .honey, lifespan: .perennial, frost: .hardy, drought: .thirsty),
             CarePreset(substrate: .peat, light: .fullSun, humidity: .saturated), .uncommon,
             "Honey-scented amber trumpets."),
            ("Pilgrim's Bladderwort",
             TraitBundle(leaf: .needle, color: .yellow, scent: .none, lifespan: .seasonal, frost: .hardy, drought: .thirsty),
             CarePreset(substrate: .peat, light: .bright, humidity: .saturated), .common,
             "Underwater bladders snap on minnows."),
            ("Hourglass Sundew",
             TraitBundle(leaf: .lance, color: .amber, scent: .citrus, lifespan: .biennial, frost: .hardy, drought: .thirsty),
             CarePreset(substrate: .sphagnum, light: .bright, humidity: .saturated), .uncommon,
             "Tentacles fold like an hourglass."),
            ("Rose-Maw Pitcher",
             TraitBundle(leaf: .ribbon, color: .rose, scent: .honey, lifespan: .perennial, frost: .hardy, drought: .thirsty),
             CarePreset(substrate: .peat, light: .bright, humidity: .saturated), .uncommon,
             "Mouth blushed rose, drawing bees."),
            ("Pale Hourglass Trap",
             TraitBundle(leaf: .lobed, color: .white, scent: .none, lifespan: .perennial, frost: .glacial, drought: .balanced),
             CarePreset(substrate: .charcoal, light: .dappled, humidity: .damp), .rare,
             "Translucent jaws, glass-like."),
            ("Sanctum Snap-Vine",
             TraitBundle(leaf: .trifid, color: .green, scent: .smoke, lifespan: .ancient, frost: .tender, drought: .thirsty),
             CarePreset(substrate: .peat, light: .dappled, humidity: .saturated), .mythic,
             "Vine of clapping traps; rumour from south.")
        ]
        for (i, e) in carns.enumerated() {
            list.append(Species(id: 64 + i, name: e.0, family: .carnivora, traits: e.1, care: e.2, rarity: e.3,
                                isBase: true, parentSpeciesIds: nil, hint: e.4))
        }
        return list
    }()
}
